
const nome = "Laylla"

try {
  nome = "Kacia"
}
catch(erro) {
  console.error('CAPTUREI UM ERRO:', erro)
}

console.log(nome)

console.log('termina aqui')
